### PR TITLE
Improve logging and callback handling

### PR DESCRIPTION
**Pull request by simontegelid**
This PR improves the logging, adds a CLI and improves how callbacks are called (schedules them instead of calling them directly). With the `automower` cli, it is easy to run a websocket session to see what's going on under the hood. Hopefully this can help debugging.

### CODE REVIEW

**Comment by simontegelid** [comment]
@Thomas55555 I have run this for a week now, both with this new CLI (which essentially is the same as the script in the readme) and integrated in home assistant without issues. I have had one glitch in home assistant, which forced me to re-enter my api-key, username and password, but the websocket and renewal of the token has run just fine apart from that (no issues with the CLI in this repo). I haven't been able to reproduce what you experienced with the websocket task not starting so it would be really helpful if you could assist a bit there. It is really nice to have all the status updates pushed immediately to home assistant!

**Comment by Thomas55555** [comment]
I just released this as a beta version, because it was not working, and I wasn't sure if there was a mistake in the dev environment. I tried it in home assistant with the latest pull from husqvarna_automower (with the 2021.9.2b in manifest.json). But I get a message, that the integration could not be loaded and I also can't delete it anymore and re-authentication is also not possible. I'm really not sure, what is worn, there is also only a warning in the logs an not an error:
```
2021-10-05 18:26:31 WARNING (MainThread) [homeassistant.config_entries] Config entry '12345678-abcd-1234-a1a1-efghijklmnop' for husqvarna_automower integration could not authenticate: None
```
I have to investigate this.

**Comment by simontegelid** [comment]
@Thomas55555 I found an issue from my side in session.connect() where I didn't refreshed the access token if it had expired, but only returned False. Since the config entry in hass is never updated after the config flow is run, it will always appear as expired on hass startup (in `async_setup_entry`). The solution is to try to refresh the access token using the refresh token if the access token appears outdated.

PR's are coming both here and in the hass integration that solves the above.

A remaining issue is that the refresh token is just valid for 10 days, so if hass is offline for 10 days, we need to login using username and password again since we don't store that in the config entry. This can only be avoided if we also store the username and password, but that is a different topic.

**Comment by simontegelid** [comment]
If you pip install the aioautomower, you should get a "automower" command in your path. Just run `automower --username mail@mail.com --password mypassword --api-key 123-123-123-123` and you should get a debug session running similar to the script above.

**Comment by simontegelid** [comment]
Try this fork: https://github.com/simontegelid/husqvarna_automower, basically the PR i made in the hass integration repo, but also using my fork of aioautomower. I'm running it now in a development env with great success.

**Comment by simontegelid** [comment]
Try to add a few more _LOGGER.debug lines in session._ws_task to see where it fails. It's sufficient to just run the `automower` cli so you don't need to include home assistant. The "connect failed" warning was my mistake, has pushed a fix for it but you can just ignore it (changed the return type of connect to None from bool).

This is what I get using the cli tool:
```
2021-10-07 08:31:42,298;DEBUG;Using selector: EpollSelector
2021-10-07 08:31:42,527;DEBUG;Resp.status get access token: 200
2021-10-07 08:31:42,817;DEBUG;Resp.status mower data: 200
2021-10-07 08:31:42,822;DEBUG;_token_monitor_task sleeping for 86338.70571446419 sec
2021-10-07 08:31:43,885;INFO;Websocket (re)connected
2021-10-07 08:31:44,339;DEBUG;Received TEXT
2021-10-07 08:31:44,339;DEBUG;Websocket ready=True (id='G0wcYej7joECJFw=')
```

**Pull request merged**
