### PR TITLE
Add websocket support

### PR DESCRIPTION
**Pull request by simontegelid**
This moves the REST stuff to its own module (still accessible on top level as before) and adds a AutomoverSession class which takes care of logging in and refreshing the access token whenever needed in the background. But more importantly; it adds support for the websocket API.

### CODE REVIEW

**Comment by Thomas55555** [comment]
Sounds interesting. Where did you get the information about the websocket? Is it documented by husqvarna?
Is the code already working?

**Comment by simontegelid** [comment]
It was mentioned here: https://github.com/Thomas55555/husqvarna_automower/issues/97 I hadn't heard about it so I googled it and found some websocket info in the API docs: https://developer.husqvarnagroup.cloud/apis/Automower+Connect+API#/readme

The code seems to do its job, I have used a script similar to the one I pasted in the readme. Feel free to try it. I'm now working on integrating it in home assistant instead of the polling.

**Comment by simontegelid** [comment]
So, now websockets are working in home assistant! No more polling :-) I will use it for a couple of days to shake out bugs, then try this PR together with the current husqvarna_automover integration to ensure that this PR is backwards compatible. Then, if you are satisfied we can merge this and I will move on with making a PR for the integration updates.

**Comment by Thomas55555** [comment]
> It was mentioned here: [Thomas55555/husqvarna_automower#97](https://github.com/Thomas55555/husqvarna_automower/issues/97) I hadn't heard about it so I googled it and found some websocket info in the API docs: https://developer.husqvarnagroup.cloud/apis/Automower+Connect+API#/readme
> 
> The code seems to do its job, I have used a script similar to the one I pasted in the readme. Feel free to try it. I'm now working on integrating it in home assistant instead of the polling.

I'm a little bit low on time, so I wait for your results.
My goal is not to store username and password of the users in home assistant. So we can leave this function
`async def login(self, username: str, password: str)` in the python module. But for the integration in home assistant, we can pass the access token from `entry.data.get(CONF_TOKEN)` to the aioautomower module.

**Comment by simontegelid** [comment]
Correct, I haven't affected how that is working so it should be fine. The websockets are still updating my mower perfectly, even slightly faster (~500ms) than the native app ;-)

**Comment by simontegelid** [comment]
I have run this for a couple of days now, both as a standalone test script just with this repo and also integrated into home assistant. This PR works both with my updated websocket integration and is backwards compatible with the current integration (running that now just for verifying). So I think this is ready to go!

**Pull request merged**
