### PR TITLE
Add inactive reasons

### PR DESCRIPTION
**Pull request by cyr-ius**
Add inactive_reasons properties for Mower class

image

### CODE REVIEW

**Comment by Thomas55555** [comment]
There are some merge conflicts and also a lot of unrelated commits. Can you have a look at that?

**Comment by cyr-ius** [comment]
All checks passed

**Comment by Thomas55555** [comment]
Can you update the fixtures as well? 
https://github.com/Thomas55555/aioautomower/blob/main/tests/fixtures/high_feature_mower.json
https://github.com/Thomas55555/aioautomower/blob/main/tests/fixtures/low_feature_mower.json

And then update the snapshots...

**Comment by cyr-ius** [comment]
I didn't pay attention to the tests directory, now it's much better.

**Comment by Thomas55555** [comment]
Thx @cyr-ius

**Pull request merged**
